"""create initial tables

Revision ID: 04fe52f10e32
Revises: 
Create Date: 2026-09-14 15:20:44.979459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04fe52f10e32'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Применить миграцию."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'completed', 'archived', name='event_status'), server_default='draft', nullable=False),
    sa.Column('total_budget', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    op.create_table('resources',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('human', 'equipment', 'venue', name='resource_type'), nullable=False),
    sa.Column('availability_per_day', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cost_per_day', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_resources_event_id_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resources'))
    )
    op.create_index(op.f('ix_resources_event_id'), 'resources', ['event_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('earliest_start', sa.Integer(), nullable=True),
    sa.Column('earliest_finish', sa.Integer(), nullable=True),
    sa.Column('latest_start', sa.Integer(), nullable=True),
    sa.Column('latest_finish', sa.Integer(), nullable=True),
    sa.Column('total_float', sa.Integer(), nullable=True),
    sa.Column('free_float', sa.Integer(), nullable=True),
    sa.Column('is_critical', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_tasks_event_id_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tasks'))
    )
    op.create_index(op.f('ix_tasks_event_id'), 'tasks', ['event_id'], unique=False)
    op.create_table('assignments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('units_allocated', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('units_allocated > 0', name=op.f('ck_assignments_units_positive')),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], name=op.f('fk_assignments_resource_id_resources'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_assignments_task_id_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assignments'))
    )
    op.create_index(op.f('ix_assignments_resource_id'), 'assignments', ['resource_id'], unique=False)
    op.create_index(op.f('ix_assignments_task_id'), 'assignments', ['task_id'], unique=False)
    op.create_table('task_dependencies',
    sa.Column('predecessor_id', sa.UUID(), nullable=False),
    sa.Column('successor_id', sa.UUID(), nullable=False),
    sa.Column('dependency_type', sa.Enum('FS', 'SS', 'FF', 'SF', name='dependency_type'), server_default='FS', nullable=False),
    sa.Column('lag_days', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.CheckConstraint('predecessor_id != successor_id', name=op.f('ck_task_dependencies_no_self')),
    sa.ForeignKeyConstraint(['predecessor_id'], ['tasks.id'], name=op.f('fk_task_dependencies_predecessor_id_tasks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['successor_id'], ['tasks.id'], name=op.f('fk_task_dependencies_successor_id_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('predecessor_id', 'successor_id', name=op.f('pk_task_dependencies'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Откатить миграцию."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_dependencies')
    op.drop_index(op.f('ix_assignments_task_id'), table_name='assignments')
    op.drop_index(op.f('ix_assignments_resource_id'), table_name='assignments')
    op.drop_table('assignments')
    op.drop_index(op.f('ix_tasks_event_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_resources_event_id'), table_name='resources')
    op.drop_table('resources')
    op.drop_table('events')
    # ENUM-типы удаляются явно: DROP TABLE их не убирает.
    op.execute("DROP TYPE IF EXISTS dependency_type")
    op.execute("DROP TYPE IF EXISTS resource_type")
    op.execute("DROP TYPE IF EXISTS event_status")
    # ### end Alembic commands ###
